# Generated by Django 5.0.6 on 2024-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsite_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='age',
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.URLField(),
        ),
    ]
