# Generated by Django 5.0.6 on 2024-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsite_app', '0004_game_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
