# Generated by Django 5.0.6 on 2024-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsite_app', '0005_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
