# Generated by Django 5.0.6 on 2024-06-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsite_app', '0006_game_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='year',
        ),
    ]
